import {
  User,
  Room,
  Contract,
  Invoice,
  IssueTicket,
  AppNotification,
  LandlordSettings,
  RealtimeTelemetry,
  JoinRequest,
  SystemLicense,
  ComplaintReport,
  SecurityEventLog,
} from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user_landlord_1',
    name: 'Nguyễn Văn Hùng',
    email: 'hung.nguyen@royalliving.vn',
    phone: '0918 293 847',
    role: 'landlord',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    idCard: '079088019284',
    hometown: 'TP. Hồ Chí Minh',
    status: 'active',
    joinedAt: '2024-01-15',
    hostCode: 'LUX99XYZ88', // 10 characters
    licenseTier: 'pro',
  },
  {
    id: 'user_landlord_2',
    name: 'Trần Thị Tuyết Mai',
    email: 'mai.tran@smartliving.com',
    phone: '0903 847 112',
    role: 'landlord',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    idCard: '001192847291',
    hometown: 'Hà Nội',
    status: 'active',
    joinedAt: '2024-03-10',
    hostCode: 'MAIHOM88KL', // 10 characters
    licenseTier: 'standard',
  },
  {
    id: 'user_tenant_1',
    name: 'Lê Minh Tuấn',
    email: 'minhtuan.dev@gmail.com',
    phone: '0982 716 384',
    role: 'tenant',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    idCard: '038200019283',
    hometown: 'Đà Nẵng',
    status: 'active',
    joinedAt: '2024-02-01',
    landlordId: 'user_landlord_1',
    roomId: 'room_201',
  },
  {
    id: 'user_tenant_2',
    name: 'Phạm Thu Hà',
    email: 'thuha.pham@design.co',
    phone: '0977 182 994',
    role: 'tenant',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    idCard: '031198002948',
    hometown: 'Hải Phòng',
    status: 'active',
    joinedAt: '2024-02-15',
    landlordId: 'user_landlord_1',
    roomId: 'room_102',
  },
  {
    id: 'user_tenant_3',
    name: 'Nguyễn Quốc Bảo',
    email: 'baonguyen@finance.vn',
    phone: '0933 718 290',
    role: 'tenant',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    idCard: '079201009182',
    hometown: 'Bình Dương',
    status: 'active',
    joinedAt: '2024-04-01',
    landlordId: 'user_landlord_1',
    roomId: 'room_301',
  },
  {
    id: 'user_tenant_new',
    name: 'Vũ Hoàng Anh',
    email: 'hoanganh.vu@tech.io',
    phone: '0912 345 678',
    role: 'tenant',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    idCard: '048202019485',
    hometown: 'Cần Thơ',
    status: 'pending_approval',
    joinedAt: '2024-08-18',
    landlordId: undefined,
  },
  {
    id: 'user_admin_1',
    name: 'Hoàng Đăng Khoa (Admin Master)',
    email: 'admin.khoa@rentalguard.vn',
    phone: '0909 000 888',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    joinedAt: '2023-12-01',
  },
];

export const INITIAL_LANDLORD_SETTINGS: LandlordSettings = {
  landlordId: 'user_landlord_1',
  houseName: 'Khu Căn Hộ & Phòng Trọ Cao Cấp Hoàng Gia (Royal Residence)',
  houseAddress: 'Số 88 Đường Nguyễn Trãi, Phường Bến Thành, Quận 1, TP. Hồ Chí Minh',
  hostCode: 'LUX99XYZ88',
  electricityRate: 3500, // 3,500 đ/kWh
  waterRate: 25000, // 25,000 đ/m3
  garbageFee: 40000, // 40,000 đ/phòng
  internetFee: 80000, // 80,000 đ/phòng (Wifi cáp quang 1Gbps)
  serviceFee: 50000, // 50,000 đ/phòng (vệ sinh hành lang & bảo trì)
  defaultDepositMonths: 1,
  
  bankCode: 'TCB',
  bankName: 'Techcombank (Ngân hàng Kỹ Thương Việt Nam)',
  accountNumber: '19038299182019',
  accountName: 'NGUYEN VAN HUNG',
  
  mainGateState: 'locked',
  mainGatePasscode: '892150',
  autoLockEnabled: true,
  autoLockTime: '23:00',
  autoUnlockTime: '05:30',
  emergencyAlarmActive: false,
  
  aiAutoBillingEnabled: true,
  aiBillingDayOfMonth: 25,
  aiAnomalyDetection: true,
  
  googleSheetWebhookUrl: 'https://script.google.com/macros/s/AKfycbyi1xXWGQy3nEBzEuO-essoeids5-5Uecz9TuTeSclxc6rRPO_foQ78BT1lpsxeO6Ig/exec',
  googleSheetSyncEnabled: true,
  googleSheetLastSync: undefined,
};

export const INITIAL_ROOMS: Room[] = [
  {
    id: 'room_101',
    landlordId: 'user_landlord_1',
    roomNumber: 'Phòng 101',
    floor: 1,
    areaM2: 26,
    basePrice: 4800000,
    amenities: ['Điều hòa Inverter', 'Tủ lạnh mini', 'Bình nóng lạnh', 'Gác lửng cao', 'Khóa thẻ từ'],
    status: 'available',
    doorLockState: 'locked',
    doorPasscode: '101992',
    securityStatus: 'secure',
    electricityMeterStart: 1240,
    waterMeterStart: 88,
    description: 'Phòng tầng 1 thoáng mát, cửa sổ lấy sáng tự nhiên, thích hợp 1-2 người ở.',
  },
  {
    id: 'room_102',
    landlordId: 'user_landlord_1',
    roomNumber: 'Phòng 102',
    floor: 1,
    areaM2: 30,
    basePrice: 5200000,
    amenities: ['Điều hòa Inverter', 'Tủ lạnh 2 cánh', 'Bình nóng lạnh', 'Bếp điện âm', 'Smart TV 43 inch', 'Khóa vân tay'],
    status: 'occupied',
    currentTenantId: 'user_tenant_2',
    currentTenantName: 'Phạm Thu Hà',
    doorLockState: 'locked',
    doorPasscode: '582910',
    securityStatus: 'secure',
    electricityMeterStart: 2150,
    waterMeterStart: 142,
    description: 'Phòng studio full nội thất gỗ sồi cao cấp, ban công đón gió.',
  },
  {
    id: 'room_201',
    landlordId: 'user_landlord_1',
    roomNumber: 'Phòng 201',
    floor: 2,
    areaM2: 35,
    basePrice: 5800000,
    amenities: ['Điều hòa Daikin 1.5HP', 'Tủ lạnh Panasonic', 'Máy giặt riêng', 'Khóa cửa thông minh IoT', 'Ban công view phố', 'Gác đúc'],
    status: 'occupied',
    currentTenantId: 'user_tenant_1',
    currentTenantName: 'Lê Minh Tuấn',
    doorLockState: 'locked',
    doorPasscode: '482910',
    securityStatus: 'secure',
    electricityMeterStart: 3820,
    waterMeterStart: 210,
    description: 'Phòng Vip tầng 2, view thoáng mát hướng Đông Nam, máy giặt riêng.',
  },
  {
    id: 'room_202',
    landlordId: 'user_landlord_1',
    roomNumber: 'Phòng 202',
    floor: 2,
    areaM2: 28,
    basePrice: 4900000,
    amenities: ['Điều hòa Inverter', 'Bình nóng lạnh', 'Bàn làm việc', 'Tủ quần áo 3 cánh'],
    status: 'available',
    doorLockState: 'locked',
    doorPasscode: '202881',
    securityStatus: 'secure',
    electricityMeterStart: 1890,
    waterMeterStart: 115,
    description: 'Phòng mới sửa sang sơn mới, sẵn sàng đón khách vào ở ngay.',
  },
  {
    id: 'room_301',
    landlordId: 'user_landlord_1',
    roomNumber: 'Phòng 301',
    floor: 3,
    areaM2: 32,
    basePrice: 5400000,
    amenities: ['Điều hòa Inverter', 'Bình nóng lạnh', 'Bếp từ', 'Khóa thông minh'],
    status: 'occupied',
    currentTenantId: 'user_tenant_3',
    currentTenantName: 'Nguyễn Quốc Bảo',
    doorLockState: 'locked',
    doorPasscode: '301772',
    securityStatus: 'secure',
    electricityMeterStart: 2450,
    waterMeterStart: 160,
    description: 'Phòng tầng 3 yên tĩnh, thích hợp người đi làm văn phòng.',
  },
  {
    id: 'room_302',
    landlordId: 'user_landlord_1',
    roomNumber: 'Phòng 302',
    floor: 3,
    areaM2: 30,
    basePrice: 5000000,
    amenities: ['Điều hòa Inverter', 'Tủ lạnh mini', 'Gác lửng gỗ'],
    status: 'maintenance',
    doorLockState: 'locked',
    doorPasscode: '302999',
    securityStatus: 'warning',
    electricityMeterStart: 980,
    waterMeterStart: 62,
    description: 'Đang bảo dưỡng hệ thống điều hòa và sơn lại tường.',
  },
];

export const INITIAL_CONTRACTS: Contract[] = [
  {
    id: 'contract_201',
    contractCode: 'HĐ-2024/HG-201',
    tenantId: 'user_tenant_1',
    tenantName: 'Lê Minh Tuấn',
    tenantPhone: '0982 716 384',
    tenantIdCard: '038200019283',
    landlordId: 'user_landlord_1',
    landlordName: 'Nguyễn Văn Hùng',
    roomId: 'room_201',
    roomNumber: 'Phòng 201',
    startDate: '2024-02-01',
    endDate: '2025-02-01',
    depositAmount: 5800000,
    monthlyRent: 5800000,
    prepaidMonthsRemaining: 0,
    terms: [
      'Bên B thanh toán tiền thuê phòng từ ngày 01 đến ngày 05 hàng tháng.',
      'Sử dụng điện nước đúng mục đích, tuân thủ an ninh trật tự và quy chế khóa cửa.',
      'Không tự ý khoan cắt, thay đổi kết cấu phòng khi chưa được sự đồng ý của Bên A.',
      'Bên A đảm bảo cung cấp dịch vụ Internet, điện nước ổn định và camera an ninh 24/7.'
    ],
    status: 'active',
    signedAt: '2024-01-28',
  },
  {
    id: 'contract_102',
    contractCode: 'HĐ-2024/HG-102',
    tenantId: 'user_tenant_2',
    tenantName: 'Phạm Thu Hà',
    tenantPhone: '0977 182 994',
    tenantIdCard: '031198002948',
    landlordId: 'user_landlord_1',
    landlordName: 'Nguyễn Văn Hùng',
    roomId: 'room_102',
    roomNumber: 'Phòng 102',
    startDate: '2024-02-15',
    endDate: '2025-02-15',
    depositAmount: 5200000,
    monthlyRent: 5200000,
    prepaidMonthsRemaining: 2, // 2 months remaining prepaid!
    prepaidUntil: '2026-10-15',
    terms: [
      'Người thuê đã thanh toán trước tiền phòng nhiều tháng theo chính sách ưu đãi.',
      'Các tháng tiếp theo chỉ xuất hóa đơn điện, nước và dịch vụ phát sinh.',
      'Giữ gìn vệ sinh chung dãy trọ.'
    ],
    status: 'active',
    signedAt: '2024-02-10',
  },
  {
    id: 'contract_301',
    contractCode: 'HĐ-2024/HG-301',
    tenantId: 'user_tenant_3',
    tenantName: 'Nguyễn Quốc Bảo',
    tenantPhone: '0933 718 290',
    tenantIdCard: '079201009182',
    landlordId: 'user_landlord_1',
    landlordName: 'Nguyễn Văn Hùng',
    roomId: 'room_301',
    roomNumber: 'Phòng 301',
    startDate: '2024-04-01',
    endDate: '2025-04-01',
    depositAmount: 5400000,
    monthlyRent: 5400000,
    prepaidMonthsRemaining: 0,
    terms: [
      'Thanh toán định kỳ hàng tháng qua VietQR.',
      'Tuân thủ nội quy giờ giấc khóa cổng chính tự động lúc 23:00.'
    ],
    status: 'active',
    signedAt: '2024-03-25',
  }
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv_2026_08_201',
    invoiceCode: 'HD-202608-201',
    landlordId: 'user_landlord_1',
    tenantId: 'user_tenant_1',
    tenantName: 'Lê Minh Tuấn',
    roomId: 'room_201',
    roomNumber: 'Phòng 201',
    monthYear: '08/2026',
    createdAt: '2026-08-20',
    dueDate: '2026-08-25',
    
    rentAmount: 5800000,
    isRentPrepaid: false,
    
    electricityStart: 3820,
    electricityEnd: 3968,
    electricityUsed: 148,
    electricityRate: 3500,
    electricityTotal: 518000,
    
    waterStart: 210,
    waterEnd: 219,
    waterUsed: 9,
    waterRate: 25000,
    waterTotal: 225000,
    
    garbageFee: 40000,
    internetFee: 80000,
    serviceFee: 50000,
    
    extraFee: 0,
    extraFeeReason: '',
    
    totalAmount: 6713000, // 5.800.000 + 518.000 + 225.000 + 170.000
    status: 'pending',
    
    bankInfo: {
      bankCode: 'TCB',
      bankName: 'Techcombank',
      accountNumber: '19038299182019',
      accountName: 'NGUYEN VAN HUNG',
      transferContent: 'HG P201 TIEN TRO T8',
    },
    aiGenerated: true,
    aiNote: 'Hóa đơn tự động tính toán từ cảm biến đo đạc IoT và biểu giá niêm yết.',
  },
  {
    id: 'inv_2026_08_102',
    invoiceCode: 'HD-202608-102',
    landlordId: 'user_landlord_1',
    tenantId: 'user_tenant_2',
    tenantName: 'Phạm Thu Hà',
    roomId: 'room_102',
    roomNumber: 'Phòng 102',
    monthYear: '08/2026',
    createdAt: '2026-08-20',
    dueDate: '2026-08-25',
    
    rentAmount: 0, // PREPAID!
    isRentPrepaid: true,
    
    electricityStart: 2150,
    electricityEnd: 2262,
    electricityUsed: 112,
    electricityRate: 3500,
    electricityTotal: 392000,
    
    waterStart: 142,
    waterEnd: 148,
    waterUsed: 6,
    waterRate: 25000,
    waterTotal: 150000,
    
    garbageFee: 40000,
    internetFee: 80000,
    serviceFee: 50000,
    
    extraFee: 0,
    
    totalAmount: 712000, // Chỉ tính điện nước dịch vụ vì đã trả trước tiền phòng
    status: 'paid',
    paidAt: '2026-08-20 14:32',
    paymentMethod: 'vietqr',
    transactionRef: 'FT2623391829',
    
    bankInfo: {
      bankCode: 'TCB',
      bankName: 'Techcombank',
      accountNumber: '19038299182019',
      accountName: 'NGUYEN VAN HUNG',
      transferContent: 'HG P102 TIEN DIEN NUOC T8',
    },
    aiGenerated: true,
    aiNote: 'Khách thuê đã đóng trước tiền phòng (còn 2 tháng). Chỉ xuất phí điện nước & sinh hoạt.',
  },
  {
    id: 'inv_2026_07_201',
    invoiceCode: 'HD-202607-201',
    landlordId: 'user_landlord_1',
    tenantId: 'user_tenant_1',
    tenantName: 'Lê Minh Tuấn',
    roomId: 'room_201',
    roomNumber: 'Phòng 201',
    monthYear: '07/2026',
    createdAt: '2026-07-20',
    dueDate: '2026-07-25',
    
    rentAmount: 5800000,
    isRentPrepaid: false,
    
    electricityStart: 3680,
    electricityEnd: 3820,
    electricityUsed: 140,
    electricityRate: 3500,
    electricityTotal: 490000,
    
    waterStart: 202,
    waterEnd: 210,
    waterUsed: 8,
    waterRate: 25000,
    waterTotal: 200000,
    
    garbageFee: 40000,
    internetFee: 80000,
    serviceFee: 50000,
    
    extraFee: 150000,
    extraFeeReason: 'Phí gửi xe máy thứ 2',
    
    totalAmount: 6810000,
    status: 'verified_by_host',
    paidAt: '2026-07-22 09:15',
    paymentMethod: 'vietqr',
    transactionRef: 'FT2620481920',
    
    bankInfo: {
      bankCode: 'TCB',
      bankName: 'Techcombank',
      accountNumber: '19038299182019',
      accountName: 'NGUYEN VAN HUNG',
      transferContent: 'HG P201 TIEN TRO T7',
    },
  }
];

export const INITIAL_ISSUES: IssueTicket[] = [
  {
    id: 'issue_01',
    ticketCode: 'SC-8812',
    tenantId: 'user_tenant_1',
    tenantName: 'Lê Minh Tuấn',
    landlordId: 'user_landlord_1',
    roomId: 'room_201',
    roomNumber: 'Phòng 201',
    category: 'nuoc',
    title: 'Vòi sen tắm bị rỉ nước liên tục',
    description: 'Vòi sen phòng tắm dù đã khóa chặt van nhưng vẫn có nước rỉ giọt tí tách suốt đêm, gây hao nước và ồn ào. Nhờ chủ nhà cho thợ sang thay gioăng cao su sớm giúp em.',
    urgency: 'medium',
    photos: ['https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&auto=format&fit=crop&q=80'],
    status: 'in_progress',
    createdAt: '2026-08-19 18:30',
    landlordNote: 'Đã hẹn thợ nước vào 9h sáng mai 22/08 để thay mới toàn bộ bộ vòi sen nóng lạnh.',
  },
  {
    id: 'issue_02',
    ticketCode: 'SC-8809',
    tenantId: 'user_tenant_2',
    tenantName: 'Phạm Thu Hà',
    landlordId: 'user_landlord_1',
    roomId: 'room_102',
    roomNumber: 'Phòng 102',
    category: 'dieu_hoa',
    title: 'Điều hòa Daikin thổi gió nhưng kém lạnh',
    description: 'Máy lạnh bật 20 độ nhưng phòng vẫn nóng, có vẻ bị hết gas hoặc màng lọc bám bụi bẩn sau thời gian dài.',
    urgency: 'high',
    photos: ['https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400&auto=format&fit=crop&q=80'],
    status: 'resolved',
    createdAt: '2026-08-15 10:15',
    resolvedAt: '2026-08-16 15:40',
    landlordNote: 'Đã nạp gas R32 và vệ sinh xịt rửa lưới lọc, máy hoạt động mát lạnh bình thường.',
  }
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif_01',
    senderId: 'user_landlord_1',
    senderName: 'Chủ trọ Nguyễn Văn Hùng',
    receiverId: 'all_tenants',
    landlordId: 'user_landlord_1',
    type: 'security_alert',
    title: 'Thông báo: Bảo trì hệ thống camera & khóa cổng chính',
    message: 'Kính gửi toàn thể quý khách thuê trọ, tối nay cổng chính sẽ tự động kích hoạt chế độ khóa điện tử thông minh từ 23:00. Quý khách vui lòng lưu mã PIN cổng chính để vào ra an toàn.',
    timestamp: '2026-08-20 20:00',
    isRead: false,
    priority: 'high',
  },
  {
    id: 'notif_02',
    senderId: 'system',
    senderName: 'Hệ thống AI Tự Động',
    receiverId: 'user_tenant_1',
    landlordId: 'user_landlord_1',
    type: 'invoice_ready',
    title: 'Hóa đơn tiền phòng & điện nước Tháng 08/2026',
    message: 'Hóa đơn kỳ Tháng 08/2026 cho Phòng 201 đã được lập với tổng tiền 6.713.000 đ. Vui lòng quét mã VietQR để thanh toán trước ngày 25/08.',
    timestamp: '2026-08-20 08:00',
    isRead: false,
    priority: 'normal',
  },
  {
    id: 'notif_03',
    senderId: 'user_landlord_1',
    senderName: 'Chủ trọ Nguyễn Văn Hùng',
    receiverId: 'all_tenants',
    landlordId: 'user_landlord_1',
    type: 'price_update',
    title: 'Thông báo: Nâng cấp đường truyền Internet cáp quang 1Gbps',
    message: 'Toàn bộ dãy trọ đã được nâng cấp hệ thống Mesh Wifi 6 tốc độ cao miễn phí phụ trội, biểu phí internet giữ nguyên 80.000 đ/phòng.',
    timestamp: '2026-08-18 14:15',
    isRead: true,
    priority: 'normal',
  }
];

export const INITIAL_JOIN_REQUESTS: JoinRequest[] = [
  {
    id: 'join_req_01',
    tenantId: 'user_tenant_new',
    tenantName: 'Vũ Hoàng Anh',
    tenantPhone: '0912 345 678',
    tenantIdCard: '048202019485',
    tenantEmail: 'hoanganh.vu@tech.io',
    hostCodeInput: 'LUX99XYZ88',
    landlordId: 'user_landlord_1',
    roomIdRequested: 'room_101',
    status: 'pending',
    createdAt: '2026-08-20 16:45',
  }
];

export const INITIAL_TELEMETRY: Record<string, RealtimeTelemetry> = {
  room_201: {
    roomId: 'room_201',
    currentKwh: 3968.4,
    currentWaterM3: 219.2,
    voltage: 221.8,
    currentAmps: 5.4,
    powerWatts: 1197.7,
    waterFlowRateLpm: 0.0,
    lastTelemetryPing: 'Vừa xong',
    dailyKwhTrend: [
      { hour: '00:00', kwh: 0.8 },
      { hour: '04:00', kwh: 0.6 },
      { hour: '08:00', kwh: 1.4 },
      { hour: '12:00', kwh: 2.1 },
      { hour: '16:00', kwh: 1.8 },
      { hour: '20:00', kwh: 3.2 },
    ],
    dailyWaterTrend: [
      { hour: '00:00', liters: 5 },
      { hour: '04:00', liters: 0 },
      { hour: '08:00', liters: 45 },
      { hour: '12:00', liters: 20 },
      { hour: '16:00', liters: 15 },
      { hour: '20:00', liters: 60 },
    ],
    aiAnomalyFlag: false,
    aiAnomalyReason: 'Chỉ số điện nước phòng 201 hoạt động ổn định.',
  },
  room_102: {
    roomId: 'room_102',
    currentKwh: 2262.1,
    currentWaterM3: 148.0,
    voltage: 222.4,
    currentAmps: 3.8,
    powerWatts: 845.1,
    waterFlowRateLpm: 0.0,
    lastTelemetryPing: 'Vừa xong',
    dailyKwhTrend: [
      { hour: '00:00', kwh: 0.5 },
      { hour: '04:00', kwh: 0.4 },
      { hour: '08:00', kwh: 1.1 },
      { hour: '12:00', kwh: 1.9 },
      { hour: '16:00', kwh: 1.2 },
      { hour: '20:00', kwh: 2.8 },
    ],
    dailyWaterTrend: [
      { hour: '00:00', liters: 0 },
      { hour: '04:00', liters: 0 },
      { hour: '08:00', liters: 35 },
      { hour: '12:00', liters: 18 },
      { hour: '16:00', liters: 10 },
      { hour: '20:00', liters: 42 },
    ],
    aiAnomalyFlag: false,
  },
  room_301: {
    roomId: 'room_301',
    currentKwh: 2510.3,
    currentWaterM3: 168.5,
    voltage: 220.9,
    currentAmps: 4.2,
    powerWatts: 927.8,
    waterFlowRateLpm: 0.2,
    lastTelemetryPing: 'Vừa xong',
    dailyKwhTrend: [
      { hour: '00:00', kwh: 0.9 },
      { hour: '04:00', kwh: 0.7 },
      { hour: '08:00', kwh: 1.3 },
      { hour: '12:00', kwh: 2.0 },
      { hour: '16:00', kwh: 1.6 },
      { hour: '20:00', kwh: 3.0 },
    ],
    dailyWaterTrend: [
      { hour: '00:00', liters: 10 },
      { hour: '04:00', liters: 5 },
      { hour: '08:00', liters: 40 },
      { hour: '12:00', liters: 25 },
      { hour: '16:00', liters: 20 },
      { hour: '20:00', liters: 55 },
    ],
    aiAnomalyFlag: false,
  }
};

export const INITIAL_LICENSES: SystemLicense[] = [
  {
    id: 'lic_01',
    landlordId: 'user_landlord_1',
    landlordName: 'Nguyễn Văn Hùng',
    plan: 'Chuyên nghiệp (Pro)',
    maxRooms: 50,
    status: 'active',
    activationKey: 'SMART-RENT-PRO-8899-ABCD',
    issuedDate: '2024-01-15',
    expiryDate: '2027-01-15',
    pricePaid: 2400000,
  },
  {
    id: 'lic_02',
    landlordId: 'user_landlord_2',
    landlordName: 'Trần Thị Tuyết Mai',
    plan: 'Cơ bản (Starter)',
    maxRooms: 15,
    status: 'active',
    activationKey: 'SMART-RENT-START-1122-WXYZ',
    issuedDate: '2024-03-10',
    expiryDate: '2025-03-10',
    pricePaid: 990000,
  }
];

export const INITIAL_COMPLAINTS: ComplaintReport[] = [
  {
    id: 'comp_01',
    userId: 'user_tenant_3',
    userName: 'Nguyễn Quốc Bảo',
    userRole: 'tenant',
    targetLandlordId: 'user_landlord_1',
    type: 'tranh_chap',
    title: 'Thắc mắc về giờ giấc khóa cổng 23:00 và việc đi làm ca đêm',
    content: 'Em thường làm ca đêm đến 23:30 mới về tới phòng, mong ban quản trị và chủ nhà cấp quyền truy cập mở cổng từ xa trên app để tiện vào trọ không cần gọi cửa làm phiền người khác.',
    status: 'resolved',
    createdAt: '2026-08-10 11:20',
    adminResponse: 'Đã xác nhận tính năng mở cổng chính từ xa qua app đã được kích hoạt cho tài khoản của bạn với mã PIN cá nhân.',
  },
  {
    id: 'comp_02',
    userId: 'user_landlord_1',
    userName: 'Nguyễn Văn Hùng',
    userRole: 'landlord',
    type: 'gop_y',
    title: 'Đề xuất bổ sung tích hợp hóa đơn điện tử tự động xuất file PDF in nhiệt',
    content: 'Hệ thống chạy rất mượt mà. Mong admin bổ sung thêm nút xuất hóa đơn định dạng phiếu thu in nhiệt A5/A6 để kẹp cùng bảng sao kê cuối tháng cho các bạn sinh viên cần nộp về trường.',
    status: 'open',
    createdAt: '2026-08-19 14:00',
  }
];

export const INITIAL_SECURITY_LOGS: SecurityEventLog[] = [
  {
    id: 'sec_01',
    landlordId: 'user_landlord_1',
    targetType: 'main_gate',
    targetLabel: 'Cổng chính dãy trọ',
    action: 'unlock_remote',
    performedBy: 'Lê Minh Tuấn',
    role: 'tenant',
    timestamp: '2026-08-21 00:15',
    success: true,
    note: 'Mở cửa vào dãy trọ bằng điều khiển từ xa qua Smart App',
  },
  {
    id: 'sec_02',
    landlordId: 'user_landlord_1',
    targetType: 'main_gate',
    targetLabel: 'Cổng chính dãy trọ',
    action: 'auto_schedule',
    performedBy: 'Hệ thống Smart Hub',
    role: 'admin',
    timestamp: '2026-08-20 23:00',
    success: true,
    note: 'Tự động kích hoạt chế độ khóa đêm theo lịch cài đặt 23:00',
  },
  {
    id: 'sec_03',
    landlordId: 'user_landlord_1',
    targetType: 'room_door',
    targetLabel: 'Khóa cửa Phòng 201',
    action: 'pin_change',
    performedBy: 'Lê Minh Tuấn',
    role: 'tenant',
    timestamp: '2026-08-15 19:30',
    success: true,
    note: 'Người thuê chủ động đổi mã PIN cửa phòng sang 482910',
  }
];
